baseURL: '/'
languageCode: 'en-us'
title: 'Pawan Chaurasia'
theme: 'typo'

taxonomies:
  tag: "tags"
  category: "categories"

googleAnalytics: "G-xxxxxxxxx"

params:
  menu:
    - name: "HOME"
      url: "/"
      weight: 1
    - name: "ME"
      url: "/me"
      weight: 2
    - name: "ENGINEERING"
      url: "/engineering"
      weight: 3
      identifier: Engineering
    - name: "ADVENTURE"
      url: "/adventure"
      weight: 4
      identifier: Adventure

  mainSections:
    - Adventure
    - Engineering

  description: "A Tech and Moto Blog"

  # Appearance settings
  theme: 'dark'
  colorPalette: 'default'
  hideHeader: false
  breadcrumbs: true
  listSummaries: true
  paginationSize: 5

  # Intro on main page, content is markdown


  # Collection to display on home
  homeCollectionTitle: 'Posts'
  homeCollection: ["adventure", "engineering"]

  isTrackerEnabled: false
  trackerDomainId: "fb8e3309-4543-48f4-b791-38aef0166f80"
  trackerBaseUrl: 'https://pagepulse-production.up.railway.app'


  # Social icons
#  social:
#    - name: "linkedin"
#      url: "https://www.linkedin.com/in/pawan-chaurasia/"
#    - name: "stackoverflow"
#      url: "https://stackoverflow.com/users/5060959/pwnchaurasia"
#    - name: "github"
#      url: "https://github.com/rjsnh1522"

  # Giscus comments
  giscus:
    enable: true
    repo: "rjsnh1522/blog_comments"
    repoid: "R_kgDONp-vFw"
    category: "Announcements"
    categoryid: "DIC_kwDONp-vF84Cl_FD"
    mapping: "pathname"
    theme: "dark"


# Lists parameters


listDateFormat: '2 Jan 2006'

# Breadcrumbs
breadcrumbs: true

# Syntax highlight on code blocks
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    style: "solarized-dark"
    lineNumbers: true
  tableOfContents:
    startLevel: 2  # Start from H2
    endLevel: 4    # Include up to H4
    ordered: false # Use bullet points instead of numbers
